language: python
python:
  - "3.8"
install:
  - pip install codecov
  - pip install coverage
  - pip install -r requirements.txt

script:
  - python -m unittest discover -s tests/

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pypi
  user: __token__
  password: $PYPI_TOKEN
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    branch: master