language: python

python:
  - "3.9"
  - "3.10"
  - "3.11"

os: linux

dist:
  - "focal"
  - "jammy"

install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov

script:
  - pytest --cov-report=xml --cov=nonparstat tests/

after_success:
  - codecov

deploy:
  provider: pypi
  user: __token__
  password: $PYPI_TOKEN
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    branch: master